testpage-jsx_profile card for viewing
IrrationalCucumber/ErrandCatcher pull request #189
Opened 2024-09-28 05:42 UTC by Lukeski91

added a ui for viewing of profile_profile card

2024-09-29 06:05 UTC, IrrationalCucumber requested changes

2024-09-29 06:05 UTC, IrrationalCucumber commented on client/src/pages/testpage.jsx
> +            {address}
Need to be editable

2024-09-29 06:05 UTC, IrrationalCucumber commented on client/src/pages/testpage.jsx
> +          <input
Adjust style because of additional input data

2024-09-29 06:05 UTC, IrrationalCucumber commented on client/src/pages/testpage.jsx
> +          <div className="upload-container">
Add style to this for uploading photo

2024-09-29 06:05 UTC, IrrationalCucumber commented on client/src/pages/testpage.jsx
> +          <textarea
Changed to textarea instead of list for user Description

2024-09-29 06:10 UTC, IrrationalCucumber commented
![image](https://github.com/user-attachments/assets/66763b9d-bff9-4d52-b194-aa2fd14fe4c2)
![image](https://github.com/user-attachments/assets/b58a2df4-6859-4ed8-b86e-d21808a6517a)
Applied profile design with adjustment

2024-09-30 13:19 UTC, Mamonde02 approved these changes

2024-10-01 03:00 UTC, IrrationalCucumber approved these changes

2024-10-01 03:00 UTC, merged